export const AGENT_REASON_CODES = {
  MISSING_CAPABILITY: "MISSING_CAPABILITY",
  TEMPLATE_SCOPE_MISMATCH: "TEMPLATE_SCOPE_MISMATCH",
  NOT_ELIGIBLE: "NOT_ELIGIBLE",
  TASK_UNSUPPORTED: "TASK_UNSUPPORTED",
  UNSUPPORTED_CHAIN: "UNSUPPORTED_CHAIN",
  INVALID_TASK_CONFIG: "INVALID_TASK_CONFIG",
  OWNER_ACTION_REQUIRED: "OWNER_ACTION_REQUIRED",
  INSUFFICIENT_FUNDING: "INSUFFICIENT_FUNDING",
} as const;

export type AgentReasonCode =
  (typeof AGENT_REASON_CODES)[keyof typeof AGENT_REASON_CODES];
